package FileService;

/**
* FileService/FileManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DocumentService.idl
* dimanche 27 octobre 2024 10 h 42 WET
*/

public final class FileManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public FileService.FileManager value = null;

  public FileManagerHolder ()
  {
  }

  public FileManagerHolder (FileService.FileManager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileService.FileManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileService.FileManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileService.FileManagerHelper.type ();
  }

}
